### ISSUE TITLE
ZCAP-LD AuthZ

### ISSUE THREAD

**Issue by llorllale** [trustbloc/hub-kms#100]
We need to support ZCAP-LD as an authorization mechanism to grant access to the following endpoints:

- `/keys`
- `/capability`
- `/export`
- `/sign`
- `/verify`
- `/encrypt`
- `/decrypt`
- `/computemac`
- `/verifymac`
- `/wrap`
- `/unwrap`

(`/keystores` will be protected with OAuth2 in a separate effort)

Each zcap's resource scope will be coarse-grained - at the keystore level - for now in this first cut. Future followups need to figure out how to reduce the scope down to individual keys (+ operation, etc.). [DigitalBazaar's webkms zcaps are coarse-grained](https://github.com/digitalbazaar/bedrock-kms-http/blob/3fafa12d2d62da4a8a8c2935c7a1265304fac528/lib/helpers.js#L155-L162). Note they have an [endpoint that generates root capabilities on demand](https://github.com/digitalbazaar/bedrock-kms-http/blob/18d125c3222fe2a30cb90d2768b327e7b2d5a4c6/lib/http.js#L203-L227).

On the other hand, perhaps issuing a coarse-grained zcap to the user scoped at the keystore-level makes sense. This zcap can have allowed actions that include `SignOperation`, `WrapKey`, etc, even while the invocation target on the zcap is the keystore.
Derived zcaps that allow using a specific key could specify the key's ID as a caveat for instance.

Breakdown:

- [x] create zcaps when creating a new KeyStore and store them. Include the client's zcap in the response. #103
- [x] design and implement middleware. #108 
  - it is possible to determine the expected invocation parameters from the request's path
- [x] rollout middleware to the 11 endpoints listsed above #108

**Comment by llorllale** [comment]
Finished with #108
