### ISSUE TITLE
Roadmap for 0.1.5

### ISSUE THREAD

**Issue by aholovko** [trustbloc/hub-kms#45]
## Key Server

- [x] Redesign functionality for creating local KMS instance (#60)
    - [x] Update SecretLock service for the KMS instance
    - [x] Move `KMSCreator` logic into its own package
- [x] Update Create Keystore API functionality (#62)
    - [x] Generate delegate key for ZCAP authorization
    - [x] Generate recipient key for SDS usage
- [x] Implement support for storing operational keys in external SDS (#61)
    - [x] Implement support for TLS CA Certs param (#77)
- [x] Implement API for exporting public key (#78)
    - [x] Pass secretlock passphrase in header instead of body (#81)
- [x] Implement Wrap/Unwrap Key API (#65)
    - [x] Sync up operations payload with Aries remote kms/crypto (#91)
- [x] Implement secretlock for Keystore KMS (#85)
- [x] Implement secretlock with shared unlock key for user's key manager (#22)
- [x] Fix issue with creating secret lock service (#110)
- [x] Implement authorization layer (should support both OAuth and ZCAP)
    - [x] ~Implement support for authorizing with oAuth token~ (#63)
    - [x] Implement support for authorizing with ZCAP-LD (#100)
- [x] ~Implement API for getting key handle (description) by key ID~ (#25)
- [x] Improve naming for used components and dependencies (#95)
- [x] Implement support for CryptoBox operations (#117)
- [x] Optimize calls to EDV and Hub Auth (#125, #126)

### Documentation

- [x] Add support for OpenAPI spec (#54)

### Technical Debt (refactoring, cleanup and chore tasks)

- [x] Refactor logging functionality (#41)
- [x] Support setting log level via param or endpoint on the fly (#52)
- [x] Do not leak the implementation details when sending back the error messages to the client (#38)
- [x] Pass KMS and Keystore services as dependencies to Operation (#29)
- [x] Update golangci-lint to 1.31.0 (#57)
- [x] Enable linter for code within pkg (#58)

## Edge Agent

- [x] Configurable aries-framework-go wasm instance
    - [x] Implement a custom aries-framework-go wasm (agent-js-worker) [#372](https://github.com/trustbloc/edge-agent/issues/372)
    - [x] Merge functionality of trustbloc-agent-js-worker and agent-js-worker [#382](https://github.com/trustbloc/edge-agent/issues/382)
- [x] ~Implement remote kms/crypto wrappers~ [#401](https://github.com/trustbloc/edge-agent/issues/401)

**Comment by aholovko** [comment]
Released by https://github.com/trustbloc/hub-kms/issues/137.
