### ISSUE TITLE
Basic end-to-end scenario for kms/crypto operations

### ISSUE THREAD

**Issue by aholovko** [trustbloc/hub-kms#7]
Goal: demonstrate a creation of user's vault for keys (keystore) with ability to generate a keypair and perform Sign/Verify operations with it via REST API.

Keystores should NOT be shared, and every keystore should have its own secretlock. Start with a single masterkey stored solely on Key Server and protected by passphrase, add an option to use Shamir Secret Sharing algorithm later.

Tasks:
- [x] Implement Create Keystore API #5 
- [x] Link keystore to a user #8
- [x] Implement API for creating key on a server for a given user #9
- [x] Implement support for masterkey lock (#17)
- [x] Implement API for Sign operation #10
- [x] Implement API for Verify operation #18
