### ISSUE TITLE
Implement API for creating key on a server for a given user

### ISSUE THREAD

**Issue by aholovko** [trustbloc/hub-kms#9]
Follow-up tickets:
- [x] Refactor to support KMS unlocking on per-keystore basis (#15)
- [x] Replace Keystore Provider mock with in-memory implementation in kms-rest (#12)
- [x] Add BDD test for "create key" API (#14)
